Skip 0 byte pseudo kernel processes
djberg96/sys-proctable pull request #106
Opened 2022-10-26 08:05 UTC by rwaffen

Fixes: #105

2022-10-26 12:21 UTC, djberg96 requested changes
I'd rather not skip everything if we don't have to if we can at least collect *some* information for the process. Personally I think we should just add `Errno::EBADF` to the list of rescued exceptions on line 346.

2022-10-26 12:44 UTC, djberg96 commented
Extra bonus points if you can integrate https://github.com/vmactions/solaris-vm :)

2022-10-27 12:35 UTC, djberg96 commented
Thanks for the update and taking a stab at the github action. However, it looks like it failed. I see `The process '/bin/bash' failed with exit code 1`.

2022-10-27 12:38 UTC, djberg96 commented on .github/workflows/ruby.yml
> +
I'm thinking we need to add a 'gem install bundler` here, followed by a `bundle install`. What do you think?

2022-10-27 12:38 UTC, djberg96 commented on .github/workflows/ruby.yml
> +          ruby -v
I think we'll want `bundle exec rake` here.

2022-10-27 12:39 UTC, djberg96 commented on .github/workflows/ruby.yml
> +    name: A job to run test in Solaris
Let's just called is "test Solaris". :)

2022-10-27 16:21 UTC, djberg96 commented
I don't think we need the `ruby -v` command do we?

Beyond that, looking at the details I see `Package runtime/ruby-26 not in catalog. Exiting.`

It's up to you if you would like to continue to pursue this, I certainly won't make it a requirement for the main fix. I just thought it would be nice to have, especially since I could then crib from it for other projects. :)

2022-10-27 16:25 UTC, rwaffen commented
ruby -v is only for testing which version would be installed, if it would install at all 🤦 
but i would say we split this, first fixing the issue and than separately trying to get this GHA working.
will remove the yaml or comment it out for the moment, so we than can continue later on.

2022-10-27 18:06 UTC, djberg96 commented
Ok, go ahead and remove it (or comment it out) and I'll re-run the jobs (which I understand won't actually be testing this change), then I'll merge it. :)

2022-10-28 11:48 UTC, djberg96 approved these changes

2022-10-28 11:49 UTC, merged